{% set version = "1.3.2" %}

package:
  name: datapackage-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/datapackage/datapackage-{{ version }}.tar.gz
  sha256: 0947eecaf829e7c0e942c64d8c57f8b2bb49433d1fa0fb81e16be495603676e4

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.10,<2.0a
    - requests >=2.8,<3.0a
    - jsonschema >=2.5,<3.0a
    - unicodecsv >=0.14,<1.0a
    - jsontableschema >=0.8,<1.0a
    - tabulator-py >=1.0.0a5,<2.0a

test:
  imports:
    - datapackage

about:
  home: https://github.com/frictionlessdata/datapackage-py
  license_file: LICENSE.md
  license: MIT
  license_family: MIT
  summary: 'Utilities to work with Data Packages as defined on dataprotocols.org'
  dev_url: https://github.com/frictionlessdata/datapackage-py
  doc_url: https://github.com/frictionlessdata/datapackage-py

extra:
  recipe-maintainers:
    - pmlandwehr
