travis:
  secure:
    BINSTAR_TOKEN: bwLKfOeZ2Y+46955UxgisZollt8VXd7NPNFJ9Q0S9ev8rSljIUrDSFoyDJCMf4NkXn5EST4mFaqcLBScafnKndzusXN9gbAadFwBS46oKDAbHXtrUV3X/WJzDRp/gG1IdyrPBOoQfIKrpiGUz2tdJLGJgYjV+WaI1AGbgU5t5zZt3DDXZIuCPVSFWP/eRUMynXyrY5WnuQhKx4XPaTtQY6OLGZtiV9ApS31NM97gP2vKykJeEnEQxupILDElFZNwfWddMFbK9NLrgke77etMw6WN6jiKSrNvgMnGQb1orhBDtQdBaEMzREToHyZmhCwZzkP2070EZjIGH+MikhAqJ4HF6Htg3FXwmyXTuowapeD5UgrRKps8dWk84DxEakaUTuyci1dipd5PhLbcHuMBATgZID7Hsk+VRxKCUvBlEzud06qFPPCIEHgmr6f2e16Rippgs9rdTQ0FUbx/wQ1/ovDzys+T0n0hR1rJfLS7G8aq6Z3M7jtopdoLxjENdZjsRPtEY1JmhCLLFazJ+/+WF4l3auiAhkRlL0saRNHxPknwMy+QSkDDe14tF2SKMd0fV9HKFAy2K2LXwYe/o00cXQ64GL7WL7cXT/a0G+ZMw5PreygAGGshEaV78DScdsjigblMRJfgdoPMgVzBmKAXDuQqv2VcFHj0qMCX8kNP7EM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
